# Generated by Django 6.0.7 on 2026-07-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='KZ', max_length=5)),
                ('deduction_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=4)),
                ('max_deduction_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
