# Generated by Django 6.0.7 on 2026-07-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrule',
            name='deduction_rate',
        ),
        migrations.RemoveField(
            model_name='taxrule',
            name='max_deduction_per_year',
        ),
        migrations.AddField(
            model_name='taxrule',
            name='cap_rate',
            field=models.DecimalField(decimal_places=2, default=0.04, max_digits=4),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='cpn_rate',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='country_code',
            field=models.CharField(default='KZ', max_length=5, unique=True),
        ),
    ]
