# Generated by Django 6.0.7 on 2026-08-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_taxrule_deduction_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxrule',
            old_name='cap_rate',
            new_name='cap_rate_standard',
        ),
        migrations.AddField(
            model_name='taxrule',
            name='cap_rate_monitored',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=4),
        ),
    ]
