# Generated by Django 6.0.7 on 2026-08-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('cover_image_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
