# Generated by Django 6.0.7 on 2026-08-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
